create table if not exists public.recipe_sections (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text default '' not null,
  sort_order integer default 0 not null,
  created_at timestamptz default now() not null
);

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.recipe_sections(id) on delete cascade,
  title text not null,
  meta text default '' not null,
  accent text default '' not null,
  tone text default '#c4873c' not null,
  sort_order integer default 0 not null,
  created_at timestamptz default now() not null
);

alter table public.recipe_sections enable row level security;
alter table public.recipes enable row level security;

create policy "public can read recipe sections"
on public.recipe_sections
for select
using (true);

create policy "public can read recipes"
on public.recipes
for select
using (true);

create index if not exists idx_recipe_sections_sort_order
  on public.recipe_sections(sort_order);

create index if not exists idx_recipes_section_sort
  on public.recipes(section_id, sort_order);
